### ISSUE TITLE
how to execute?

### ISSUE THREAD

**Issue by dragonGRaf** [Kief5555/GeForceNow-Afk#1]
idk mac and idk how to execute the script
how do i do that?

**Comment by Kief5555** [comment]
> idk mac and idk how to execute the script how do i do that?

Script editor -> File -> open -> select file -> play button

**Comment by dragonGRaf** [comment]
forgot this was open i googled it 
a bit easier i think
https://osxdaily.com/2016/08/19/run-applescript-command-line-macos-osascript/

**Comment by Kief5555** [comment]
> forgot this was open i googled it 
> 
> a bit easier i think
> 
> https://osxdaily.com/2016/08/19/run-applescript-command-line-macos-osascript/

That works too. Script editor allows you to change which keys are sent and the delay between them. Easier permissions management too.

**Comment by dragonGRaf** [comment]
> > forgot this was open i googled it
> > a bit easier i think
> > https://osxdaily.com/2016/08/19/run-applescript-command-line-macos-osascript/
> 
> That works too. Script editor allows you to change which keys are sent and the delay between them. Easier permissions management too.

ye i just use text editor or script editor to edit the keys that are send and use the terminal to start xD
